server:
  port: ${API_SERVER_PORT}
  name: ${SERVER_NAME}
  servlet:
    context-path: ${CONTEXT_PATH}

spring:
  application:
    name: monitoring
  datasource:
    url: jdbc:${DB}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: ${FETCH_SIZE}
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

excel-info:
  file-base-url: ${FILE_BASE_URL}
  excel-extension: ${EXCEL_EXTENSION}

minio:
  bucket:
    excel: ${MINIO_BUCKET_EXCEL}
    csv: ${MINIO_BUCKET_CSV}
  access:
    key: ${MINIO_KEY}
    secret: ${MINIO_SECRET}
  url: ${MINIO_URL}

sse:
  timeout: ${SSE_TIMEOUT}

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USER}
  password: ${RABBITMQ_PASSWORD}
  exchange:
    direct-exchange: ${DIRECT_EXCHANGE}
    file-create-progress-exchange: ${FILE_CREATE_PROGRESS_EXCHANGE}
    file-create-error-exchange: ${FILE_CREATE_ERROR_EXCHANGE}
  queue:
    file-create-progress-queue: ${FILE_CREATE_PROGRESS_QUEUE}
    file-create-error-queue: ${FILE_CREATE_ERROR_QUEUE}
  routing-key:
    file-create-request-routing-key: ${FILE_CREATE_REQUEST_ROUTING_KEY}
    csv-update-request-routing-key: ${CSV_UPDATE_REQUEST_ROUTING_KEY}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: test-name