server:
  port: ${API_SERVER_PORT}

spring:
  datasource:
    url: jdbc:${DB}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: ${FETCH_SIZE}
    jpa:
      open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${EXCHANGE_NAME}
      routing-key: ${ROUTING_KEY}
      default-receive-queue: ${QUEUE_NAME}
    listener:
      simple:
        concurrency: ${CONCURRENCY}
        max-concurrency: ${MAX_CONCURRENCY}
        prefetch: ${PREFETCH}
        acknowledge-mode: manual

excel-info:
  file-base-url: ${FILE_BASE_URL}
  excel-extension: ${EXCEL_EXTENSION}

minio:
  bucket:
    name: ${MINIO_BUCKET}
  access:
    key: ${MINIO_KEY}
    secret: ${MINIO_SECRET}
  url: ${MINIO_URL}

sse:
  timeout: ${SSE_TIMEOUT}