server:
  port: ${API_SERVER_PORT}

spring:
  datasource:
    url: jdbc:${DB}://${HOST}:${PORT}/${DB_NAME}
    username: ${USER}
    password: ${PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: ${FETCH_SIZE}

minio:
  bucket:
    name: ${MINIO_BUCKET}
  access:
    key: ${MINIO_KEY}
    secret: ${MINIO_SECRET}
  url: ${MINIO_URL}