server:
  port: ${API_SERVER_PORT}
  name: ${SERVER_NAME}

spring:
  datasource:
    url: jdbc:${DB}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: ${FETCH_SIZE}
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  application:
    name: ${SERVER_NAME}

excel-info:
  file-base-url: ${FILE_BASE_URL}
  excel-extension: ${EXCEL_EXTENSION}

minio:
  bucket:
    name: ${MINIO_BUCKET}
  access:
    key: ${MINIO_KEY}
    secret: ${MINIO_SECRET}
  url: ${MINIO_URL}

sse:
  timeout: ${SSE_TIMEOUT}

rabbitmq:
  direct-exchange: ${DIRECT_EXCHANGE}
  file-create-progress-exchange: ${FILE_CREATE_PROGRESS_EXCHANGE}
  file-create-request-queue: ${FILE_CREATE_REQUEST_QUEUE}
  file-create-request-routing-key: ${FILE_CREATE_REQUEST_ROUTING_KEY}